### ISSUE TITLE
elm_code: Right click > paste causes no keyboard input.

### ISSUE THREAD

**Issue by NuLogicSystems** [Obsidian-StudiosInc/ecrire#14]
Right click again restores the keyboard input.

**Comment by wltjr** [comment]
I am not able to replicate, likely not following same steps. Can you please describe the steps to replicate? I assume you mean;
1. Right click paste text
2. Try to enter text after

Something seems off with that right click paste stuff. All function and code is in elm_code, but seems something in ecrire causes problems. Given the duplicate paste that can only be replicated in ecrire for some reason with the elm_cnp stuff.

**Comment by NuLogicSystems** [comment]
Yes, paste text into ecrire using right click and try to type, nothing types.
You can either right click again, click on the titlebar (like your going to move the window), click on the bottom bar, try to resize window, or use any of the buttons or menu functions. In other words, it sort of looses keyboard focus. Moving focus away from the input field, and then back again, fixes it.

**Comment by wltjr** [comment]
Interesting, unfortunately I am not able to replicate. Are you using EFL 1.20.4 or git? Also what version of E? Though think its likely an EFL vs E problem. Are you able to replicate in elm tests or edi? Thanks!

**Comment by NuLogicSystems** [comment]
I'm using git master most of the time.
I just checked, and yes, I can reproduce this in elm test.

**Comment by wltjr** [comment]
Sounds like an elm_code bug in git EFL. Which is a new issue that did not exist. In addition to the duplicate paste with right click. Seems that whole right click handling is rather buggy.

**Comment by NuLogicSystems** [comment]
I just remembered that marcel has been working focus lately, maybe the issue is in there.
This could also be a clipboard issue. I'll mention this to him and see what we can come up with.

**Comment by wltjr** [comment]
Possibly but elm_code tends to deviate from the normal stuff pretty heavily. Most things are ajwilliams and al/netstar.

**Comment by NuLogicSystems** [comment]
I'm not sure what you mean, but Marcel (bu5hm4n) has been working on all aspects of focus lately:
https://git.enlightenment.org/core/efl.git/log/

**Comment by wltjr** [comment]
Its hard to explain. If you experience issues in elm_code not in other widgets that is the easiest way to explain. I bet the issues you are experiencing do not show in anything else. I am not sure about focus, but any elm_code bugs tend to be worked on by others as well as elm_code development.
https://git.enlightenment.org/core/efl.git/log/?qt=grep&q=elm_code

**Comment by wltjr** [comment]
Finally able to replicate this on 1.20.5. It seems to be another 2nd paste issue. I can type after the first paste, but not the 2nd.

It is a focus related issue!

Elm code does something unique when it has focus. The line the cursor is on turns black. You can clearly see on the 2nd paste when you cannot type. The line becomes grey. Indicating that elm_code lost focus. If you click in the text area of ecrire. You will notice it turns black again and you are able to type. Thus it is clearly losing focus. You likely could type if focus remained.

That it only triggers on 2nd paste. Makes me think it has something to do with the other duplicate paste issue. Though maybe unrelated. Both are triggered on 2nd paste. Not sure what makes that special. I guess some boolean or something is being toggled. Thus it works fine on 1st paste, but on 2nd it does not.

**Comment by wltjr** [comment]
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by andydotxyz** [comment]
I cannot replicate locally with the latest focus code in EFL

**Comment by NuLogicSystems** [comment]
@ajwillia-ms 
Is that efl-git or efl 1.20.6?

**Comment by andydotxyz** [comment]
efl-git - focus code was in the middle of being changed in 1.20.6 so if it's on that version it would be great to know if it is resolved on master.

**Comment by NuLogicSystems** [comment]
I can still reproduce the after second paste it looses focus in the code editor on EFL 1.20.6.
After second paste I can't hit enter and have to click in the box again to get the keyboard back.

Steps to reproduce:
- paste a line in code editor
- hit enter for a new line
- paste again on second line
- focus is no longer on code editor
- click back in code editor box
- can now use keyboard again

**Comment by andydotxyz** [comment]
Is it possible to test efl-git? This may already be fixed upstream

**Comment by NuLogicSystems** [comment]
I'll try on my test machine later. This one needs to remain on stable releases.

**Comment by wltjr** [comment]
@ajwillia-ms this still exists in 1.20.7-pre. Not sure if anything was fixed in EFL regarding focus or an elm_code specific issue. I can replicate in Elementary tests and EDI. Just as said above. The cursor goes away is the obvious tell.

After the first paste from right click, the cursor is at the end of the pasted text. When you right click and paste again, the 2nd time. The cursor does not show at the end of the pasted text. If you right click to paste again, the 3rd time, a cursor shows up again. On the 4th, it goes away. So every other.

**Comment by wltjr** [comment]
Ah I just came across this, but after talking to @haxworx seems its resolved in git, so will close when 1.21 is released.

**Comment by wltjr** [comment]
Tested in released EFL 1.21.0. I could not replicate the original issue. Able to type text after right click paste. Seems resolved, closing.
