### ISSUE TITLE
elm_code: First character being bold when using line numbers < 10 lines

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/ecrire#18]
A bug in elm_code causing the first letter of some or all lines to be bold. This is related to the line numbers. Which the margin also seems to change size, and is a bit wonky there.

![shot-2017-11-11_12-31-37](https://user-images.githubusercontent.com/12835340/32691889-bb003582-c6dc-11e7-92d9-daa655b0b6d0.jpg)
![shot-2017-11-11_12-29-48](https://user-images.githubusercontent.com/12835340/32691882-948e4e52-c6dc-11e7-8927-03f8f32b3309.jpg)
![shot-2017-11-11_12-30-23](https://user-images.githubusercontent.com/12835340/32691890-bd4e93b0-c6dc-11e7-9399-f5a6d08a391c.jpg)

More than 10 lines it seems to go away. Not able to replicate >= 10 lines
![shot-2017-11-11_12-30-34](https://user-images.githubusercontent.com/12835340/32691888-b8ddbac2-c6dc-11e7-8b54-0c400460a9dd.jpg)

The margin should not change and numbers be right aligned for consistency. If left aligned properly spaced.
![shot-2017-11-11_12-33-42](https://user-images.githubusercontent.com/12835340/32691884-96ca3c94-c6dc-11e7-86f7-47a85212f54f.jpg)

**Comment by wltjr** [comment]
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by andydotxyz** [comment]
I cannot see which upper case you are referring to - do you mean bold typeface?
Either way I cannot replicate locally - is it possibly related to the font being used?

**Comment by wltjr** [comment]
Yes upper was a mistake, I meant bold. Sorry for that mistake. Big difference in meaning. In this case I have no custom font set.

**Comment by andydotxyz** [comment]
Thanks. As EFL does not install a default font it would still be helpful to know what font you are using - Elm_Code picks up the first Monospace font returned by fontconfig.

**Comment by wltjr** [comment]
Noto sans font. I do not believe it is font specific. Knowing what font EFL is using is another issue I brought up [early on](https://phab.enlightenment.org/T5453). Even went to [fontconfig](https://bugs.freedesktop.org/show_bug.cgi?id=100935) to see about possible solutions. Plus discussions on list etc. I cannot create a proper Font selection dialog, as I have no clue what the font in use by default is....

**Comment by andydotxyz** [comment]
Can you please screenshot it in elementary_test so I can do a pixel comparison locally?

**Comment by wltjr** [comment]
Here you go, the first line f is bold, 2nd line and others its not. It is only the first character when that happens.
![shot-2017-11-24_17-50-50](https://user-images.githubusercontent.com/12835340/33225144-31f2ac8e-d140-11e7-8d9e-c58a02432837.jpg)

**Comment by andydotxyz** [comment]
Why should it not be yellow? It certainly looks like a number to me.

**Comment by wltjr** [comment]
Yeah you are correct. I was in text mode not code. Being syntax above makes obvious sense. I will remove to not confuse, and back to original issue. Which seems to be related to the line numbers on the left.

Relating to that, it would be nice to have it not be gray and just be what ever color the background is like leafpad or others. Makes it look odd and stands out a bit much. Along with the alignment thing that cause it to change size as the numbers increase. Sure with thousands, but when you go from 1 to 2 digits it looks odd visually. Not sure 3 matters as much or the rest, but kinda the same. Not much you can do with a new document. But > 10 lines is likely to be assumed 99% of the time. I would likely assume 3 digits. That is not eating up to much space like in leafpad screenshots. Checking it out in netbeans it pads to 2 digits by default and grows 3+. Either 2 or 3, but 1 seems bit to little and funky when it grows.  Though maybe also because of right alignment vs left.

**Comment by andydotxyz** [comment]
Resolved upstream https://phab.enlightenment.org/T6444

**Comment by wltjr** [comment]
Great thanks, many more to go. I will close after next EFL release once no longer visible. Thanks!

**Comment by wltjr** [comment]
Resolved in EFL 1.20.7. Thanks @ajwillia-ms
