### ISSUE TITLE
Blinking cursor size doesn't correspont to the font size

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#22]
If you use a custom font and size it up a bit the blinking line cursor is smaller than the text. It also doesn't line up nicely with the text.

**Comment by wltjr** [comment]
Yep I can confirm that. elm_code has tons of issues. I wish the developers would spend more time fixing bugs and looking for new ones. Stuff like this and others effects all elm_code. Which includes EDI, the E IDE which I cannot see how anyone can use that. Given the amount of issues for ecrire being a text editor. If I was writing code with all these issues.... Clear why I do not use EDI and use Netbeans instead. It really bothers me the quality of Ecrire is effected by the quality of code used, as in elm_code. Which has tremendous bugs... Many of which are not being fixed as authors focus on other areas.... In the line wrap bug, they forgot about the old one and opened another...

**Comment by wltjr** [comment]
Adding upstream so they are aware of issues
@Enlightenment @ajwillia-ms @zmike

**Comment by andydotxyz** [comment]
When registering an "upstream bug" it would be very helpful if someone linked the bug in the upstream bug tracker. That way it will get scheduled for next release, where possible.

**Comment by wltjr** [comment]
It would be helpful if others did not [disable peoples](https://phab.enlightenment.org/p/wltjr/) account so they could do that... For now others must file bugs and link them. I linked most upstream bugs here but I do not believe I provided cross links, link from upstream to here.

**Comment by andydotxyz** [comment]
As per your email to the group today you have another account and have decided not to file bugs using it.
That said I am sure, as you say, that others could do that if you won't.

**Comment by wltjr** [comment]
Why should I be forced to use another account while the main one I use people can recognize me at remains disabled? I do not file bugs out of respect. If others wanted me to file bugs they would not have disabled my main account. That argument makes no sense what so ever.

I bet most of these issues you are not aware of. They have filed some other bugs in phab. Others can do many things I will not, but they do not. So I guess that stuff just doesn't get done. All would be a non issue if account wasn't disabled. Which wouldn't be the case if well, once again others did not act when they did not need to. The result surely has not helped make anything better. Though you may feel better. It is not producing better quality products or software.

**Comment by andydotxyz** [comment]
I have unsubscribed from this thread. The content of the latest message is a continuation of an argument that was already making me feel unwell.

**Comment by wltjr** [comment]
@ajwillia-ms the amount of bugs in elm_code,EFL, and E makes me feel unwell. Much less the attitudes of the community. I regret ever taking your suggestion to switch to elm_code... Though being both a man and an adult. I can handle feeling unwell and other stuff...

**Comment by andydotxyz** [comment]
This was kindly fixed upstream by netstar

**Comment by wltjr** [comment]
Great thanks @haxworx and @ajwillia-ms! I will close it once EFL 1.21 is released. Thanks!

**Comment by wltjr** [comment]
Confirmed resolved in 1.21, will close once released.

**Comment by wltjr** [comment]
Confirmed resolved in released 1.21.0, closing.
