### ISSUE TITLE
Parallel compiling fails

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/ecrire#3]
Fails to build with parallel jobs, requires make -j1 for now. It tries to build the code before the language translations, causing the build to fail.

**Comment by ApostolosB** [comment]
Today i build like i always do with -j2 and it worked. If you don't see anything weird close this and i'll file a new bug in case i have any build issues again.

**Comment by wltjr** [comment]
That is good news, though I suspect it mail fail again not sure. If it does can revisit.
