### ISSUE TITLE
Background removal caused non adjustable transparent bottom box

### ISSUE THREAD

**Issue by wltjr** [Obsidian-StudiosInc/ecrire#34]
##### Description
In fixing issue #29 removing the background caused the bottom box to become transparent. Seems a background is needed, but the previous way was not respecting the alpha value. It was never transparent, which caused it to become white. Inversion switched that to black, but was unable to get any transparency. Maybe an issue in EFL, not sure.

##### System information
- EFL 1.20 or 1.21

**Comment by wltjr** [comment]
Looks like some sort of issue or regression in ```efl_bg_add```. The object it creates does not respect alpha values at all using ```evas_object_color_set``` It is always a solid color.

**Comment by ApostolosB** [comment]
@wltjr can you check it this is fixed?

**Comment by wltjr** [comment]
I am waiting on upstream to figure out the regressions with elm_bg. There is some problem where the background does not respect transparency. If I add it back, it lose it else where. Though I may since once they fix it upstream, it will be fixed here. Likely better to have no transparency than transparent bottom.

**Comment by ApostolosB** [comment]
Mike said he fixed some stuff and doesn't see it on his machine. I get it on mine (git). No idea what is going on.

**Comment by wltjr** [comment]
Give me a bit I will add back the background and you can build from git. Worse case you do not get transparency. I fixed the all white issue, which is sort of related. Before the RGB and Alpha did not effect each other, they were independent. They switched to premultipled colors. Where the RGB cannot be greater than the Alpha and ends up like Ra, Ba, Ga, where the alpha is part of each. So i just set all to the alpha value now. That fixed everything being white per issue #29.

**Comment by ApostolosB** [comment]
yep. the alpha slider in settings doesn't do much i believe.

Anyway better than the transparent box.

**Comment by wltjr** [comment]
It makes the inner stuff transparent, but with a solid background it just reduces visibility. It still works in EFL 1.20.7 but not 1.21-beta1. Not sure about git, I have to add back alpha adjustment on background. If I add it for 1.21* or git, it looks like https://github.com/Obsidian-StudiosInc/ecrire/issues/29#issuecomment-411141830

**Comment by ApostolosB** [comment]
TBH i am ok with the fixed transparent bottom box. I don't see a use for transparent backgrounds. For my use cases at least.

Thanks for the fix.

**Comment by wltjr** [comment]
The transparency is pretty moot. It was just something that could be done in EFL, thus showing that off. I do like it for some things. My terminology backgrounds are transparent. Though it was something I added to my theme, so windows become transparent on drag. Still miss wobbly windows.
