### ISSUE TITLE
Please add the cmake option variable to enable/disable NLS

### ISSUE THREAD

**Issue by yurivict** [Obsidian-StudiosInc/ecrire#35]
When the port option is set to OFF it should be able to turn it off.

Thanks!

**Comment by yurivict** [comment]
Currently, the build fails when gettext isn't found. Also the library ```libintl``` shouldn't be linked when it is disabled.

**Comment by wltjr** [comment]
Thanks for the report! I am looking into making the necessary changes. The ```libintl``` was added for FreeBSD in issue #1. It should have been added to the conditional for gettext. Which I will add another conditional based on a NLS option.

**Comment by wltjr** [comment]
This e57ef1c should fix the issue, though need to confirm ```ENABLE_NLS``` works on FreeBSD.  But it should fix any issues with that disabled, unset or ```ENABLE_NLS=false``` or other acceptable disable format.

**Comment by yurivict** [comment]
You need to remove calls to ```libintl_bindtextdomain``` when ```NLS=off```.

**Comment by wltjr** [comment]
Thanks see if c6c81eb fixes that. Not sure why that did not fail for me in test builds with ```ENABLE_NLS``` not set. It was not making the PO files. This was all pre-existing from when I took over the project. Thanks for helping to improve with testing and reporting issues!

**Comment by yurivict** [comment]
Now it works fine on FreeBSD, thanks!

**Comment by wltjr** [comment]
Great, is that both ways, NLS enabled and disabled? If your able to test both. Sounds like it definitely works for at least disabled. Thanks for testing and reporting!

**Comment by yurivict** [comment]
Yes, for both NLS enabled and disabled.Thanks for fixing it!

**Comment by wltjr** [comment]
Excellent, and you are welcome. Let me know if you encounter any other issues. Thanks!
