### ISSUE TITLE
No text visible with EFL 1.21.0

### ISSUE THREAD

**Issue by NuLogicSystems** [Obsidian-StudiosInc/ecrire#36]
Tittle explains it all:
http://www.enlightenment.org/ss/e-5b78e171c77f99.01431619.jpg

**Comment by wltjr** [comment]
I am not able to replicate this. Text shows for me using latest tag, which is presently the same as git head. Need to find a way to replicate in order to address.

**Comment by NuLogicSystems** [comment]
It was my Manjaro dark theme that was based on the elementary default theme.
Evidently they changed the way the elementery advanced entries work, they now use the theme.
So now, I need to update my Manjaro theme again to merge in the changes required for the advanced entries to work properly.
I totally forgot that I posted this issue here, I apologize for that.

**Comment by wltjr** [comment]
No worries, they had some theme related issue with elm_code so was not sure if that was related or not. You can theme aspects of elm_code now you could not before. I [added one](https://github.com/Obsidian-StudiosInc/eminence/blob/master/src/elementary/edc/elm/code.edc) to my theme eminence. you may want to reference. Basically [same as in EFL](https://github.com/Enlightenment/efl/blob/master/data/elementary/themes/edc/elm/code.edc), but with some theme specific changes.

Either way glad it not an issue. Still have to restore Transparency via some means, now that it is possible again. Hopefully no other issues. Need to close several once I do a final confirmation test.

**Comment by NuLogicSystems** [comment]
Yes, elm_code is the issue I think.
It's these tests that gave me the issue:
https://www.enlightenment.org/ss/display.php?image=e-5b79be9527ec23.05179944.jpg

Nothing else in elm test did.
Ecrire just happened to be the place that I first noticed the issue.
