### ISSUE TITLE
Save and Save As don't stay highlighted after a second change

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#41]
##### Description
Description of issue
As the title suggests

##### Steps to reproduce
1. Open a file
2. Change something 
3. Save highlights > Click it
4. Change something again
5. Save doesn't get highlighted.
...

##### System information
- EFL Version = 1.21
- E Version = 0.22.4
- X or Wayland = wayland

**Comment by wltjr** [comment]
This should be resolved now
