### ISSUE TITLE
Saving after hiting the X to close on the top bar doesn't make Ecrire close

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#42]
##### Description
Description of issue
Closing from X and selecting save  from the popup doesnt close ecrire.

##### Steps to reproduce
1. Open ecrire 
2. Type something
3. Hit X to close 
4. Choose save from the popup
5. Ecrire doesn't close. (no idea if it saves though). Expected behavior should be save and exit.

##### System information
- EFL Version = 1.21
- E Version = 0.22.4
- X or Wayland = wayland

**Comment by wltjr** [comment]
I need to add more logic here so it remembers the close action triggered the file save and should exit after. Right now it just uses the regular file save logic. Which does not close after. Only if you discard does it close. Same with using the file close button.

**Comment by ApostolosB** [comment]
Yes. Discard closes.

**Comment by wltjr** [comment]
This should be fixed now.
