### ISSUE TITLE
Save and Save as don't highlight after paste on new doc.

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#44]
##### Description
Description of issue
As the title suggests. You have to type something in the doc to get them to appear.

##### Steps to reproduce
1. Open a new ecrire win
2. Copy and paste some text
3. The save and save as options are not available
...

##### System information
- EFL Version - 1.21.1
- E Version - 0.22.4
- X or Wayland - Wayland

**Comment by wltjr** [comment]
Thanks for the report. How are you doing the copy and paste? Via right click, paste button, or 3rd mouse button. I will check all three, just curious if it was any one in particular. I assume all have the same issue.

**Comment by ApostolosB** [comment]
Tested with middle button, ctrl-c/v, and rclick copy rclick paste and all behave the same.

**Comment by wltjr** [comment]
Great thanks for checking. Hopefully solving for one should for all. I will work on this ASAP, hopefully later today. I assume redo/undo may need addressing as well. Those usually trigger along with the others to reflect a document has been modified via some means.

**Comment by wltjr** [comment]
That should fix this issue. If not I will reopen and work on it more. Thanks again for the report!
