### ISSUE TITLE
Redo stays highlighted even if the action can't be redone.

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#5]
To rep:

Type something > hit undo > hit enter a few times > redo still highlighted.

**Comment by wltjr** [comment]
Thanks for the report I will look into ASAP

**Comment by wltjr** [comment]
I think this is a lag effect. Go try to click on redo and see if it stays highlighted. It seems to be staying highlighted up till the moment I go to click it. Like it is being changed, just not updated. This also seems to happen in reverse. The undo stays highlighted with nothing left to undo. Till you click on the entry area again. Not sure if this is an elm code bug or something else, could be ecrire specific not sure. Seems it should be updating but is lagging, which would not be ecrire code I do not think.

**Comment by wltjr** [comment]
Think this is a bit better now. There is only 1 case where I could still replicate an issue with the first character entered after a series of operations. On the 2nd character redo was disabled. That does not seem to occur with hitting enter. Though I have seen some other odd stuff with undo actions removing improper characters etc. Not sure exactly about that.

**Comment by wltjr** [comment]
@ApostolosB  Pretty sure with recent changes I made today this is now fully resolved. Using both buttons and ctrl-z/y, both redo and undo seem to function as expected now. Neither say highlighted when you can no longer do either redo or undo. If you can confirm and close if resolved for you. Thank you!

**Comment by ApostolosB** [comment]
Seems ok. Thanks :)
