### ISSUE TITLE
No focus on startup

### ISSUE THREAD

**Issue by Peter2121** [Obsidian-StudiosInc/ecrire#51]
##### Description
There is no focus inside text area on startup. If I try to enter something on my keyboard or press `Ctrl-V `to paste any text - nothing happens. I must click inside text area, then it gets focus and text can be entered inside.

##### Steps to reproduce
1. Start `ecrire`
2. Try to input some text

##### System information
- EFL Version: GIT
- E Version: GIT
- X or Wayland: X

**Comment by Peter2121** [comment]
...even if I paste something using toolbar icon (it works) - there is still no focus in the text area!

**Comment by wltjr** [comment]
Sorry for the delay, it looks like the main menu bar is causing some issues. If you go to settings and uncheck Show Menu, then focus works in the main text area. I am looking into why the main menu is preventing focus from the text area.
