### ISSUE TITLE
Paste on the bar doesn't work reliably.

### ISSUE THREAD

**Issue by ApostolosB** [Obsidian-StudiosInc/ecrire#6]
Start a new ecrire window > type a word >select it with the mouse > copy or cut > the paste option doesn't get highlighted.
If you hit enter some times and paste something with rclick>paste then it gets highlighted.

I've also seen it add characters at the end of a paste. Weird.

**Comment by wltjr** [comment]
Thanks for the report I will look into ASAP

**Comment by wltjr** [comment]
This seems to be an elm code bug, I have opened [task T5507](https://phab.enlightenment.org/T5507)

**Comment by wltjr** [comment]
EFL 1.19.1 addressed the missing "selection,start" but is still missing "selection,copy" and "selection,cut". Which will not work till the next release of EFL. Code is there in ecrire for when ever it is implemented in EFL. This bug will remain open till at least next EFL release.

**Comment by wltjr** [comment]
This was resolved in 1.20.1, so closing. I will push a commit in a bit with minimum requirement for that version.
