### ISSUE TITLE
Crash on deleting spaces

### ISSUE THREAD

**Issue by NuLogicSystems** [Obsidian-StudiosInc/ecrire#7]
When editing a line that has too many spaces before the first character with either the delete key, or with the backspace key, crashes ecrire with no warning and on random number of deletes.

**Comment by wltjr** [comment]
Thanks, not sure if that is an elm code issue or ecrire. Likely elm code unless something with ecrire callbacks is causing an issue. I will see if I can replicate.

**Comment by wltjr** [comment]
Can you see if this remains with EFL 1.19.1? I am not able to replicate. If it does still occur. Can you provide reproducible steps? Thanks!

**Comment by NuLogicSystems** [comment]
It's random, let me see if I can record it.

**Comment by wltjr** [comment]
Ok no problem. Also see if you can replicate with Elementary test. That will confirm if its elm code or ecrire specific. Thank you!

**Comment by NuLogicSystems** [comment]
I've tried vokoscreen, recordmydesktop and simple screen recorder.
I can't seem to capture the desktop, I just get a bunch of flickering apps on the desktop.

**Comment by NuLogicSystems** [comment]
OK, I had vsync turned on in the compositor that was interfering with recording..
https://www.dropbox.com/s/z1p4oswavva6sfv/vokoscreen-2017-05-22_18-57-28.mp4?dl=0
https://www.dropbox.com/s/hcpymnvehz9o4vf/vokoscreen-2017-05-22_18-59-15.mp4?dl=0

**Comment by NuLogicSystems** [comment]
What test in elm test would I use to test this issue?

**Comment by wltjr** [comment]
In Elementary test app the search box, type in code. There are 3, Code Editor, Code Entry Markup, and Code Syntax. Usually it will occur in the first, Code Editor. That is the one I use the most, but should occur in any of the 3.

**Comment by wltjr** [comment]
Ah ok I was able to replicate with your videos. Seems the key to trigger is make sure the cursor is at the very start of the line. I was able to replicate once with elementary test as well. I cannot reliable replicate in the tests as I can in ecrire. Not sure what that means yet.

**Comment by wltjr** [comment]
Opened upstream [task T5516](https://phab.enlightenment.org/T5516)

**Comment by wltjr** [comment]
@NuLogicSystems is this still occurring for you using EFL 1.20.0 beta 3? I am no longer getting crashes. This may be resolved in EFL 1.20 release. Thanks for time checking!

**Comment by NuLogicSystems** [comment]
I'm still getting crashes adding text in some of my files, but not in deleting any text in the same files.
I'm not sure if this answer helps, or not.

**Comment by NuLogicSystems** [comment]
Oops, spoke too soon. It just crashed on me when deleting text.
This file usually crashes on me: https://www.dropbox.com/s/aase4h6azwxz182/PKGBUILD.txt?dl=0

**Comment by wltjr** [comment]
Adding text would be a new issue or related to the deleting spaces maybe. Likely a new issue. I will check out that file thanks. I was using the other big file you provided before. It just hangs on that one for me now, till it runs out of memory and crashes. I commented on the phab bug.

**Comment by wltjr** [comment]
I opened a new issue [T5771](https://phab.enlightenment.org/T5771) for the crash adding text. Likely need to open one here as well. I had opened another upstream I did not here [T5504](https://phab.enlightenment.org/T5504), crash when pressing enter on long lines. I think the issue with crashing on characters is related. At least seems to be for me.

**Comment by wltjr** [comment]
Seems both these were resolved in 1.20.1. Can you confirm?

**Comment by NuLogicSystems** [comment]
Yes, I can confirm.
